/*
 * Ticket Management System API
 * REST API pour le système de gestion de tickets avec authentification utilisateur et admin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AssignTicketRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-11-01T21:19:28.577-04:00")
public class AssignTicketRequest {
  @SerializedName("adminId")
  private Integer adminId = null;

  public AssignTicketRequest adminId(Integer adminId) {
    this.adminId = adminId;
    return this;
  }

   /**
   * ID de l&#39;administrateur à qui assigner le ticket
   * @return adminId
  **/
  @ApiModelProperty(example = "1", required = true, value = "ID de l'administrateur à qui assigner le ticket")
  public Integer getAdminId() {
    return adminId;
  }

  public void setAdminId(Integer adminId) {
    this.adminId = adminId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignTicketRequest assignTicketRequest = (AssignTicketRequest) o;
    return Objects.equals(this.adminId, assignTicketRequest.adminId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignTicketRequest {\n");
    
    sb.append("    adminId: ").append(toIndentedString(adminId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

