/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.49-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AdminResponse;
import io.swagger.model.ErrorResponse;
import io.swagger.model.TicketResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-11-01T21:15:30.678-04:00")

@Validated
@Api(value = "admins", description = "the admins API")
//@RequestMapping(value = "/api")
@RequestMapping(value = "")
public interface AdminsApi {

    @ApiOperation(value = "Récupérer les tickets assignés à un admin", nickname = "getAdminAssignedTickets", notes = "Retourne tous les tickets assignés à un administrateur", response = TicketResponse.class, responseContainer = "List", tags={ "Admins", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Liste des tickets assignés", response = TicketResponse.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Admin introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/admins/{adminId}/tickets",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<TicketResponse>> getAdminAssignedTickets(@ApiParam(value = "ID de l'administrateur",required=true) @PathVariable("adminId") Integer adminId);


    @ApiOperation(value = "Récupérer tous les administrateurs", nickname = "getAllAdmins", notes = "Liste tous les administrateurs du système", response = AdminResponse.class, responseContainer = "List", tags={ "Admins", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Liste des administrateurs", response = AdminResponse.class, responseContainer = "List") })
    @RequestMapping(value = "/admins",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<AdminResponse>> getAllAdmins();

}
