/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.49-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.LoginRequest;
import io.swagger.model.LoginResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-11-01T21:15:30.678-04:00")

@Validated
@Api(value = "auth", description = "the auth API")
//@RequestMapping(value = "/api")
@RequestMapping(value = "")
public interface AuthApi {

    @ApiOperation(value = "Connexion utilisateur ou admin", nickname = "login", notes = "Authentification par email pour utilisateur ou administrateur", response = LoginResponse.class, tags={ "Authentication", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Connexion réussie", response = LoginResponse.class),
        @ApiResponse(code = 401, message = "Email invalide ou utilisateur introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<LoginResponse> login(@ApiParam(value = "Informations de connexion" ,required=true )  @Valid @RequestBody LoginRequest body);

}
