/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.49-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AddCommentRequest;
import io.swagger.model.AssignTicketRequest;
import io.swagger.model.CreateTicketRequest;
import io.swagger.model.ErrorResponse;
import io.swagger.model.TicketResponse;
import io.swagger.model.UpdateStatusRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-11-01T21:15:30.678-04:00")

@Validated
@Api(value = "tickets", description = "the tickets API")
//@RequestMapping(value = "/api")
@RequestMapping(value = "")
public interface TicketsApi {

    @ApiOperation(value = "Ajouter un commentaire à un ticket", nickname = "addComment", notes = "Permet à un utilisateur d'ajouter un commentaire à son ticket", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Commentaire ajouté", response = TicketResponse.class),
        @ApiResponse(code = 403, message = "Utilisateur non autorisé à commenter ce ticket", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Ticket introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/{ticketId}/comments",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TicketResponse> addComment(@ApiParam(value = "ID du ticket",required=true) @PathVariable("ticketId") Integer ticketId,@ApiParam(value = "Commentaire à ajouter" ,required=true )  @Valid @RequestBody AddCommentRequest body);


    @ApiOperation(value = "Assigner un ticket à un admin", nickname = "assignTicket", notes = "Permet d'assigner un ticket à un administrateur", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ticket assigné avec succès", response = TicketResponse.class),
        @ApiResponse(code = 400, message = "Assignation impossible (ticket déjà assigné ou statut incorrect)", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Ticket ou admin introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/{ticketId}/assign",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<TicketResponse> assignTicket(@ApiParam(value = "ID du ticket",required=true) @PathVariable("ticketId") Integer ticketId,@ApiParam(value = "ID de l'admin à assigner" ,required=true )  @Valid @RequestBody AssignTicketRequest body);


    @ApiOperation(value = "Fermer un ticket", nickname = "closeTicket", notes = "Met le statut du ticket à TERMINE", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ticket fermé", response = TicketResponse.class),
        @ApiResponse(code = 400, message = "Impossible de fermer le ticket", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Ticket introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/{ticketId}/close",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<TicketResponse> closeTicket(@ApiParam(value = "ID du ticket",required=true) @PathVariable("ticketId") Integer ticketId);


    @ApiOperation(value = "Créer un nouveau ticket", nickname = "createTicket", notes = "Création d'un ticket par un utilisateur", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Ticket créé avec succès", response = TicketResponse.class),
        @ApiResponse(code = 400, message = "Données invalides", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TicketResponse> createTicket(@ApiParam(value = "Données du nouveau ticket" ,required=true )  @Valid @RequestBody CreateTicketRequest body);


    @ApiOperation(value = "Récupérer tous les tickets (admin uniquement)", nickname = "getAllTickets", notes = "Retourne la liste complète des tickets", response = TicketResponse.class, responseContainer = "List", tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Liste des tickets", response = TicketResponse.class, responseContainer = "List"),
        @ApiResponse(code = 403, message = "Accès refusé", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<TicketResponse>> getAllTickets();


    @ApiOperation(value = "Récupérer un ticket par ID", nickname = "getTicketById", notes = "Retourne les détails d'un ticket spécifique", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Détails du ticket", response = TicketResponse.class),
        @ApiResponse(code = 404, message = "Ticket introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/{ticketId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<TicketResponse> getTicketById(@ApiParam(value = "ID du ticket",required=true) @PathVariable("ticketId") Integer ticketId);


    @ApiOperation(value = "Récupérer les tickets d'un utilisateur", nickname = "getUserTickets", notes = "Retourne tous les tickets créés par un utilisateur spécifique", response = TicketResponse.class, responseContainer = "List", tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Liste des tickets de l'utilisateur", response = TicketResponse.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Utilisateur introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/user/{userId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<TicketResponse>> getUserTickets(@ApiParam(value = "ID de l'utilisateur",required=true) @PathVariable("userId") Integer userId);


    @ApiOperation(value = "Mettre à jour le statut d'un ticket", nickname = "updateTicketStatus", notes = "Change le statut d'un ticket (OUVERT -> ASSIGNE -> VALIDATION -> TERMINE)", response = TicketResponse.class, tags={ "Tickets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Statut mis à jour", response = TicketResponse.class),
        @ApiResponse(code = 400, message = "Transition de statut invalide", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "Ticket introuvable", response = ErrorResponse.class) })
    @RequestMapping(value = "/tickets/{ticketId}/status",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<TicketResponse> updateTicketStatus(@ApiParam(value = "ID du ticket",required=true) @PathVariable("ticketId") Integer ticketId,@ApiParam(value = "Nouveau statut" ,required=true )  @Valid @RequestBody UpdateStatusRequest body);

}
