/*
 * Ticket Management System API
 * REST API pour le système de gestion de tickets avec authentification utilisateur et admin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.AdminResponse;
import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.TicketResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminsApi
 */
@Ignore
public class AdminsApiTest {

    private final AdminsApi api = new AdminsApi();

    
    /**
     * Récupérer les tickets assignés à un admin
     *
     * Retourne tous les tickets assignés à un administrateur
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAdminAssignedTicketsTest() throws Exception {
        Integer adminId = null;
        List<TicketResponse> response = api.getAdminAssignedTickets(adminId);

        // TODO: test validations
    }
    
    /**
     * Récupérer tous les administrateurs
     *
     * Liste tous les administrateurs du système
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllAdminsTest() throws Exception {
        List<AdminResponse> response = api.getAllAdmins();

        // TODO: test validations
    }
    
}
